#!/usr/bin/env bash
# Recording toolchain bootstrap. Generic: do not edit this file per project.
#
# Puts a pinned vhs + ttyd + ffmpeg into demo/.toolchain/bin and, on Linux
# without the usual desktop libraries, vendors the handful of shared objects
# the headless Chromium that vhs drives needs. Everything lands inside the
# repo; nothing is installed system-wide and nothing needs root.
#
# Exports: TOOLCHAIN_BIN, and PATH / LD_LIBRARY_PATH additions.

set -euo pipefail

# vhs 0.12.x starts Chromium, captures frames, then silently writes no file on
# some Linux boxes (charmbracelet/vhs frame-encoding step exits without an
# error). 0.10.0 is the newest release that encodes reliably headless, so it is
# pinned rather than tracking latest.
VHS_VERSION="0.10.0"
TTYD_VERSION="1.7.7"
FFMPEG_URL="https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"

TOOLCHAIN_DIR="${TOOLCHAIN_DIR:?bootstrap.sh needs TOOLCHAIN_DIR}"
TOOLCHAIN_BIN="$TOOLCHAIN_DIR/bin"
TOOLCHAIN_SYSROOT="$TOOLCHAIN_DIR/sysroot"

log() { printf '  %s\n' "$*" >&2; }
have() { command -v "$1" >/dev/null 2>&1; }

ensure_vhs() {
  [ -x "$TOOLCHAIN_BIN/vhs" ] && return 0
  log "fetching vhs $VHS_VERSION"
  local url="https://github.com/charmbracelet/vhs/releases/download/v${VHS_VERSION}/vhs_${VHS_VERSION}_Linux_x86_64.tar.gz"
  local work
  work="$(mktemp -d)"
  curl -fsSL "$url" -o "$work/vhs.tar.gz"
  tar xzf "$work/vhs.tar.gz" -C "$work"
  find "$work" -name vhs -type f -exec install -m 0755 {} "$TOOLCHAIN_BIN/vhs" \;
  rm -rf "$work"
}

ensure_ttyd() {
  if have ttyd; then return 0; fi
  [ -x "$TOOLCHAIN_BIN/ttyd" ] && return 0
  log "fetching ttyd $TTYD_VERSION"
  curl -fsSL \
    "https://github.com/tsl0922/ttyd/releases/download/${TTYD_VERSION}/ttyd.x86_64" \
    -o "$TOOLCHAIN_BIN/ttyd"
  chmod 0755 "$TOOLCHAIN_BIN/ttyd"
}

ensure_ffmpeg() {
  if have ffmpeg; then return 0; fi
  [ -x "$TOOLCHAIN_BIN/ffmpeg" ] && return 0
  log "fetching ffmpeg (static build)"
  local work
  work="$(mktemp -d)"
  curl -fsSL "$FFMPEG_URL" -o "$work/ffmpeg.tar.xz"
  tar xf "$work/ffmpeg.tar.xz" -C "$work"
  find "$work" -maxdepth 2 -name ffmpeg -type f -exec install -m 0755 {} "$TOOLCHAIN_BIN/ffmpeg" \;
  find "$work" -maxdepth 2 -name ffprobe -type f -exec install -m 0755 {} "$TOOLCHAIN_BIN/ffprobe" \;
  rm -rf "$work"
}

# vhs drives a headless Chromium that it downloads itself into ~/.cache/rod.
# On a server image the graphics/crypto libraries that Chromium links against
# are often absent. Rather than asking for root, fetch those .deb files and
# unpack them next to the toolchain.
declare -A LIB_PACKAGES=(
  [libnss3.so]="libnss3"
  [libnssutil3.so]="libnss3"
  [libsmime3.so]="libnss3"
  [libnspr4.so]="libnspr4"
  [libplds4.so]="libnspr4"
  [libplc4.so]="libnspr4"
  [libasound.so.2]="libasound2t64 libasound2"
  [libatk-1.0.so.0]="libatk1.0-0t64 libatk1.0-0"
  [libatk-bridge-2.0.so.0]="libatk-bridge2.0-0t64 libatk-bridge2.0-0"
  [libcups.so.2]="libcups2t64 libcups2"
  [libdrm.so.2]="libdrm2"
  [libgbm.so.1]="libgbm1"
  [libxkbcommon.so.0]="libxkbcommon0"
  [libpango-1.0.so.0]="libpango-1.0-0"
  [libcairo.so.2]="libcairo2"
)

find_chromium() {
  local candidate
  for candidate in "$HOME"/.cache/rod/browser/*/chrome; do
    [ -x "$candidate" ] && { printf '%s' "$candidate"; return 0; }
  done
  return 1
}

missing_libraries() {
  local chrome="$1"
  LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}" ldd "$chrome" 2>/dev/null \
    | awk '/not found/ { print $1 }' | sort -u
}

vendor_browser_libraries() {
  local chrome missing packages package
  chrome="$(find_chromium)" || return 0   # not downloaded yet; nothing to check
  missing="$(missing_libraries "$chrome")"
  [ -z "$missing" ] && return 0

  packages=""
  while read -r lib; do
    [ -z "$lib" ] && continue
    packages="$packages ${LIB_PACKAGES[$lib]:-}"
  done <<<"$missing"

  if ! have apt-get || ! have dpkg-deb; then
    log "headless Chromium is missing:$(echo "$missing" | tr '\n' ' ')"
    log "install the matching packages for your distro, then re-run"
    return 0
  fi

  log "vendoring Chromium libraries:$(echo $packages | tr ' ' '\n' | sort -u | tr '\n' ' ')"
  mkdir -p "$TOOLCHAIN_SYSROOT" "$TOOLCHAIN_DIR/debs"
  ( cd "$TOOLCHAIN_DIR/debs"
    for package in $(echo $packages | tr ' ' '\n' | sort -u); do
      # Names moved around in the Ubuntu t64 transition; try each candidate.
      apt-get download "$package" >/dev/null 2>&1 || true
    done )
  for package in "$TOOLCHAIN_DIR/debs"/*.deb; do
    [ -e "$package" ] || continue
    dpkg-deb -x "$package" "$TOOLCHAIN_SYSROOT"
  done

  local extra
  extra="$(find "$TOOLCHAIN_SYSROOT" -name '*.so*' -printf '%h\n' 2>/dev/null | sort -u | tr '\n' ':')"
  export LD_LIBRARY_PATH="${extra}${LD_LIBRARY_PATH:-}"
}

bootstrap_toolchain() {
  mkdir -p "$TOOLCHAIN_BIN"
  ensure_vhs
  ensure_ttyd
  ensure_ffmpeg
  export PATH="$TOOLCHAIN_BIN:$PATH"
  vendor_browser_libraries
}
