#!/usr/bin/env bash
# One download, retried properly. Generic: do not edit this file per project.
#
# Why this exists, with a date on it: on 2026-09-11, mid-verification of the
# third portfolio piece, GitHub's release CDN started returning HTTP 500 for
# exactly one asset (ttyd 1.7.7) while every other asset on the same host
# served fine. `make demo` died on the spot with a raw `curl: (22)` and a
# non-zero exit, on a repo whose entire promise is "one command, from nothing".
# The download was fine ninety seconds later.
#
# A demo that a five-minute CDN blip turns into a broken repo is a demo that
# fails in front of the client rather than in front of me. So every fetch in
# demo/lib/ goes through here: a few attempts, a widening gap between them, and
# a message that distinguishes "the network is having a moment" from "the URL
# is wrong", because those need different responses from whoever is reading.
#
# Nothing runs at source time. Usage:
#
#   . "$(dirname "${BASH_SOURCE[0]}")/fetch.sh"
#   fetch_url "$url" "$dest" || <handle it>
#
# Returns non-zero after the last attempt; callers decide whether that is fatal
# (vhs.sh: yes, there is no recording without it) or a fallback (uv.sh: no, try
# python3 -m venv instead).

FETCH_ATTEMPTS="${FETCH_ATTEMPTS:-3}"
FETCH_BACKOFF="${FETCH_BACKOFF:-3}"

fetch_log() { printf '  %s\n' "$*" >&2; }

# Curl exit codes worth trying again. 22 is an HTTP >=400 with -f, which covers
# the 500 above; 6/7 are DNS and connection failures; 28 is a timeout; 56 is a
# connection reset mid-transfer. A 404 also arrives as 22, which is why the
# final message says what to check rather than asserting which it was.
fetch_url() {
  local url="$1" dest="$2" attempt=1 code delay

  command -v curl >/dev/null 2>&1 || { fetch_log "curl is not installed"; return 1; }

  while :; do
    # The `else` is load-bearing: after a plain `fi`, $? is the status of the
    # if-statement (0 when no branch ran), not of curl, so capturing it there
    # reports every failure as "curl 0" and throws away the one number that
    # separates "the host is having a moment" from "the URL is wrong".
    if curl -fsSL --connect-timeout 20 --max-time 300 "$url" -o "$dest"; then
      return 0
    else
      code=$?
    fi
    if [ "$attempt" -ge "$FETCH_ATTEMPTS" ]; then
      break
    fi
    delay=$((FETCH_BACKOFF * attempt))
    fetch_log "download failed (curl $code), retrying in ${delay}s [$attempt/$((FETCH_ATTEMPTS - 1))]"
    sleep "$delay"
    attempt=$((attempt + 1))
  done

  fetch_log "could not download after $FETCH_ATTEMPTS attempts (curl $code): $url"
  fetch_log "  if this is a 5xx the host is having a moment and it is worth re-running;"
  fetch_log "  if it is a 404 the pinned version is gone and the URL needs updating."
  rm -f "$dest"
  return 1
}
