#!/usr/bin/env bash
# Generic Python environment bootstrap. Do not edit this file per project.
#
# Every Python piece needs the same ladder: use the machine's uv if it has one,
# fetch a pinned uv if it does not, fall back to `python3 -m venv`, and fail
# with an actionable message if neither works. In the first two pieces that
# ladder lived in demo/setup.sh — a file the README calls project-specific —
# which meant the third piece would copy thirty lines and change one string.
# That is forking, not reusing, so it moved here. What is left in setup.sh is
# the part that genuinely differs per piece.
#
# Nothing runs at source time. Usage:
#
#   . "$DEMO_DIR/lib/python-venv.sh"
#   ensure_venv .venv "bs4 openpyxl"
#
# Arguments: the venv directory, and the import names that prove the install
# worked. The second is optional but worth passing: it is what turns "the venv
# exists" into "the venv is usable", and it catches a half-finished install
# from an interrupted first run.
#
# Tunable by the caller before the call, not by editing this file:
#   VENV_PYTHON_VERSION   interpreter uv should supply      (default 3.12)
#   VENV_INSTALL_TARGET   what to pip-install               (default .[dev])

VENV_PYTHON_VERSION="${VENV_PYTHON_VERSION:-3.12}"
VENV_INSTALL_TARGET="${VENV_INSTALL_TARGET:-.[dev]}"

# shellcheck source=uv.sh
. "$(dirname "${BASH_SOURCE[0]}")/uv.sh"

venv_log() { printf '  %s\n' "$*" >&2; }

ensure_venv() {
  local venv="${1:-.venv}" imports="${2:-}"
  local py="$venv/bin/python" uv abs_venv

  case "$venv" in /*) abs_venv="$venv" ;; *) abs_venv="$PWD/$venv" ;; esac

  if [ ! -x "$py" ]; then
    if uv="$(ensure_uv)"; then
      venv_log "creating $venv with uv"
      # --python lets uv supply the interpreter when the machine has no 3.12 of
      # its own, which is the whole point of bootstrapping it.
      "$uv" venv --python "$VENV_PYTHON_VERSION" "$venv" >/dev/null
      VIRTUAL_ENV="$abs_venv" "$uv" pip install --quiet -e "$VENV_INSTALL_TARGET"
    elif python3 -m venv --help >/dev/null 2>&1 && python3 -c 'import ensurepip' 2>/dev/null; then
      venv_log "creating $venv with python -m venv"
      python3 -m venv "$venv"
      "$py" -m pip install --quiet --upgrade pip
      "$py" -m pip install --quiet -e "$VENV_INSTALL_TARGET"
    else
      # Last resort: we could neither fetch uv nor use the system python.
      echo "setup: could not fetch uv (see the log above) and this python3 has no" >&2
      echo "  ensurepip. Install uv (https://astral.sh/uv) or your distro's python3-venv" >&2
      echo "  package, then re-run." >&2
      return 1
    fi
  fi

  if [ -n "$imports" ]; then
    # One import statement, so the first missing name is the one reported.
    if ! "$py" -c "import ${imports// /,}" 2>/dev/null; then
      echo "setup: $venv exists but its dependencies are missing or broken." >&2
      echo "  Expected to import: $imports" >&2
      echo "  Delete $venv and re-run." >&2
      return 1
    fi
  fi
}
