#!/usr/bin/env bash
# Pinned uv bootstrap. Generic: do not edit this file per project.
#
# A clean checkout is not a clean machine. Stock Ubuntu 24.04 ships a python3
# with no ensurepip (that lives in the separate python3-venv package) and no
# uv, so "create a virtualenv" fails before a single line of project code
# runs — which takes `make test`, `make run` and `make demo` down with it.
#
# So fetch uv the same way lib/vhs.sh fetches vhs/ttyd and lib/ffmpeg.sh
# fetches ffmpeg: a pinned
# release, unpacked inside the repo, no root and nothing system-wide. uv then
# supplies the interpreter too, so the machine does not even need python3.12.
#
# Nothing runs at source time. Usage:
#
#   . "$DEMO_DIR/lib/uv.sh"
#   if UV="$(ensure_uv)"; then ... ; else <fallback> ; fi
#
# ensure_uv prints a path to a working uv on stdout and logs to stderr, or
# returns non-zero if there is no uv and the fetch did not work.

UV_VERSION="0.12.13"

# shellcheck source=fetch.sh
. "$(dirname "${BASH_SOURCE[0]}")/fetch.sh"

# demo/.toolchain, matching record.sh, unless the caller already chose one.
if [ -z "${TOOLCHAIN_DIR:-}" ]; then
  TOOLCHAIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.toolchain"
fi

uv_log() { printf '  %s\n' "$*" >&2; }

# The release asset names are <arch>-<vendor>-<os>; pick ours or fail loudly
# enough that the caller can fall back instead of downloading nonsense.
uv_target_triple() {
  local os arch
  case "$(uname -s)" in
    Linux)  os="unknown-linux-gnu" ;;
    Darwin) os="apple-darwin" ;;
    *) return 1 ;;
  esac
  # Alpine and friends have no glibc, and uv ships a separate musl build.
  if [ "$os" = "unknown-linux-gnu" ] && ldd --version 2>&1 | grep -qi musl; then
    os="unknown-linux-musl"
  fi
  case "$(uname -m)" in
    x86_64|amd64)  arch="x86_64" ;;
    aarch64|arm64) arch="aarch64" ;;
    *) return 1 ;;
  esac
  printf '%s-%s' "$arch" "$os"
}

# Guards against a truncated or corrupted download. The checksum comes from
# the same origin as the tarball, so it is not a defence against a compromised
# release — pinning the version is what bounds that.
uv_verify_checksum() {
  local tarball="$1" expected_file="$2" expected actual
  expected="$(cut -d' ' -f1 <"$expected_file")"
  [ -n "$expected" ] || return 1
  if command -v sha256sum >/dev/null 2>&1; then
    actual="$(sha256sum "$tarball" | cut -d' ' -f1)"
  elif command -v shasum >/dev/null 2>&1; then
    actual="$(shasum -a 256 "$tarball" | cut -d' ' -f1)"
  else
    uv_log "no sha256sum or shasum available; skipping checksum verification"
    return 0
  fi
  [ "$actual" = "$expected" ]
}

uv_fetch() {
  local dest="$1" triple url work
  triple="$(uv_target_triple)" || {
    uv_log "no pinned uv build for $(uname -s)/$(uname -m)"
    return 1
  }
  command -v curl >/dev/null 2>&1 || { uv_log "curl is not installed"; return 1; }

  url="https://github.com/astral-sh/uv/releases/download/${UV_VERSION}/uv-${triple}.tar.gz"
  uv_log "fetching uv $UV_VERSION ($triple)"

  work="$(mktemp -d)"
  # No `set -e` bail-out here: a failed fetch is a fallback, not a crash.
  # fetch_url retries a transient failure and has already said so on stderr.
  if ! fetch_url "$url" "$work/uv.tar.gz"; then
    rm -rf "$work"
    return 1
  fi
  # The checksum is advisory — one retry, quietly, so a missing .sha256 costs a
  # second rather than the full backoff ladder.
  if FETCH_ATTEMPTS=2 FETCH_BACKOFF=1 fetch_url "$url.sha256" "$work/uv.sha256" 2>/dev/null; then
    if ! uv_verify_checksum "$work/uv.tar.gz" "$work/uv.sha256"; then
      uv_log "checksum mismatch on the uv download"
      rm -rf "$work"
      return 1
    fi
  else
    uv_log "could not fetch the published checksum; continuing unverified"
  fi
  if ! tar xzf "$work/uv.tar.gz" -C "$work"; then
    uv_log "could not unpack the uv archive"
    rm -rf "$work"
    return 1
  fi

  mkdir -p "$(dirname "$dest")"
  # The archive unpacks to uv-<triple>/uv; find it rather than assume depth.
  if ! find "$work" -name uv -type f -exec install -m 0755 {} "$dest" \; ; then
    rm -rf "$work"
    return 1
  fi
  rm -rf "$work"
  [ -x "$dest" ]
}

# PATH first (respect what the machine already has), then a copy we fetched
# earlier, then fetch one.
ensure_uv() {
  local dest="$TOOLCHAIN_DIR/bin/uv"
  if command -v uv >/dev/null 2>&1; then
    command -v uv
    return 0
  fi
  if [ -x "$dest" ]; then
    printf '%s' "$dest"
    return 0
  fi
  uv_fetch "$dest" || return 1
  printf '%s' "$dest"
}
