#!/usr/bin/env bash
# Regenerate the demo clip from scratch, headless, on synthetic sample data.
#
# Generic orchestrator: bootstrap the recording toolchain, run the project's
# setup, play the tape, check the result. Do not edit this file per project.
# The two files you change for a new piece are demo/setup.sh and demo/demo.tape.
#
#   ./demo/record.sh            regenerate demo/out/demo.gif
#   ./demo/record.sh --clean    throw the toolchain away first

set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"
TOOLCHAIN_DIR="$DEMO_DIR/.toolchain"
OUT_DIR="$DEMO_DIR/out"
TAPE="$DEMO_DIR/demo.tape"
MAX_SECONDS="${MAX_SECONDS:-35}"

if [ "${1:-}" = "--clean" ]; then
  rm -rf "$TOOLCHAIN_DIR"
fi

export TOOLCHAIN_DIR
# shellcheck source=lib/bootstrap.sh
. "$DEMO_DIR/lib/bootstrap.sh"

say() { printf '\033[1m==>\033[0m %s\n' "$*" >&2; }

say "bootstrapping recording toolchain"
bootstrap_toolchain

say "preparing the project"
"$DEMO_DIR/setup.sh"

say "recording $(basename "$TAPE")"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

play_tape() (
  cd "$REPO_ROOT"
  vhs "$TAPE"
)

# The first run on a fresh machine is also what downloads headless Chromium.
# If that run fails, vendor whatever libraries it turned out to need and retry
# exactly once.
if ! play_tape; then
  say "first attempt failed; checking headless Chromium libraries"
  vendor_browser_libraries
  play_tape
fi

# vhs exits 0 having written nothing on some Linux boxes (see lib/bootstrap.sh),
# and it does that per Output line. Check every target the tape names rather
# than trusting the exit code, or a missing MP4 ships quietly.
MISSING=0
while read -r target; do
  [ -n "$target" ] || continue
  if [ ! -s "$REPO_ROOT/$target" ]; then
    echo "record.sh: the tape names $target but vhs wrote no such file" >&2
    MISSING=1
  fi
done <<<"$(grep -E '^[[:space:]]*Output[[:space:]]' "$TAPE" | awk '{print $2}')"
[ "$MISSING" -eq 0 ] || exit 1

# sort, so the file the duration is reported for is the same one every run.
CLIP="$(find "$OUT_DIR" -maxdepth 1 -type f \( -name '*.gif' -o -name '*.mp4' \) | sort | head -1)"
if [ -z "$CLIP" ] || [ ! -s "$CLIP" ]; then
  echo "record.sh: the tape produced no clip" >&2
  exit 1
fi

if command -v ffprobe >/dev/null 2>&1; then
  DURATION="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$CLIP" 2>/dev/null || echo "")"
else
  DURATION=""
fi

# Report every file the tape produced, not only the one the duration is
# measured from, so the operator can see the MP4 landed too.
for file in "$OUT_DIR"/*; do
  [ -f "$file" ] || continue
  say "wrote ${file#"$REPO_ROOT"/} ($(du -h "$file" | cut -f1))"
done

if [ -n "$DURATION" ] && [ "${DURATION%.*}" -gt "$MAX_SECONDS" ]; then
  echo "record.sh: clip is ${DURATION%.*}s, over the ${MAX_SECONDS}s budget" >&2
  exit 1
fi
if [ -n "$DURATION" ]; then
  say "clip is ${DURATION%.*}s, inside the ${MAX_SECONDS}s budget"
fi
