#!/usr/bin/env bash
# Regenerate the demo clip from scratch, headless, on synthetic sample data.
#
# Generic orchestrator: pick a recipe, run the project's setup, bootstrap the
# recipe's toolchain, record, check the result. Do not edit this file per
# project. The files you change for a new piece are demo/recipe, demo/setup.sh
# and whichever of demo/scene.py (Playwright) or demo/demo.tape (VHS) your
# recipe uses.
#
#   ./demo/record.sh                    regenerate demo/out/ with demo/recipe
#   ./demo/record.sh --clean            throw the toolchain away first
#   DEMO_RECIPE=vhs ./demo/record.sh    override the recipe for one run
#
# A recipe is demo/lib/<name>.sh and must define two functions:
#   recipe_bootstrap        fetch whatever it needs, no root, inside the repo
#   recipe_record OUT_DIR   leave a clip in OUT_DIR, optionally set RECIPE_CLIP
#
# The output directory is wiped before the recipe runs, so everything kept in
# it has to be rebuilt by the recording. Anything that was there and is not
# afterwards is put back and the run fails -- see restore_unrebuilt below.

set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"
TOOLCHAIN_DIR="$DEMO_DIR/.toolchain"
MAX_SECONDS="${MAX_SECONDS:-35}"

# Each recipe gets its own output directory when asked for one, so a repo that
# ships clips from two recipes does not have one wipe the other.
OUT_DIR="${DEMO_OUT_DIR:-$DEMO_DIR/out}"
case "$OUT_DIR" in /*) ;; *) OUT_DIR="$REPO_ROOT/$OUT_DIR" ;; esac

if [ "${1:-}" = "--clean" ]; then
  rm -rf "$TOOLCHAIN_DIR"
fi

RECIPE="${DEMO_RECIPE:-}"
if [ -z "$RECIPE" ] && [ -f "$DEMO_DIR/recipe" ]; then
  # First non-comment, non-blank line.
  RECIPE="$(grep -v '^[[:space:]]*#' "$DEMO_DIR/recipe" | grep -v '^[[:space:]]*$' | head -1 | tr -d '[:space:]')"
fi
RECIPE="${RECIPE:-vhs}"

RECIPE_LIB="$DEMO_DIR/lib/$RECIPE.sh"
if [ ! -f "$RECIPE_LIB" ]; then
  echo "record.sh: no recipe '$RECIPE'. Available:" >&2
  # A recipe is a lib file that defines recipe_record; everything else in lib/
  # is a shared helper. Asking the files what they are beats keeping a list of
  # the ones to skip, which is a list that goes stale the next time lib/ grows.
  for candidate in "$DEMO_DIR"/lib/*.sh; do
    grep -q '^recipe_record()' "$candidate" || continue
    echo "  $(basename "$candidate" .sh)" >&2
  done
  exit 1
fi

export TOOLCHAIN_DIR DEMO_DIR REPO_ROOT
RECIPE_CLIP=""

say() { printf '\033[1m==>\033[0m %s\n' "$*" >&2; }

# --fresh is the recording's one extra demand on setup.sh: a scene that opens
# on output from an earlier run is a lie about what the first command does.
# What "fresh" means is the piece's business, because only setup.sh knows which
# directories this project writes; record.sh only knows that it is recording.
# Every other caller (every `make` target) runs setup.sh without it and keeps
# its output. A piece with nothing to wipe can ignore the flag; a piece that
# rejects unknown arguments, as this one does, must accept --fresh.
say "preparing the project"
"$DEMO_DIR/setup.sh" --fresh

# shellcheck source=/dev/null
. "$RECIPE_LIB"

for required in recipe_bootstrap recipe_record; do
  if ! declare -F "$required" >/dev/null; then
    echo "record.sh: $RECIPE_LIB does not define $required()" >&2
    exit 1
  fi
done

say "bootstrapping the $RECIPE toolchain"
recipe_bootstrap

# OUT_DIR is wiped below and that is deliberate: a recording that inherits a
# frame from the last one is not a recording of this commit. But OUT_DIR is
# also where the *committed* artifacts live, and a recipe only rebuilds the
# ones it produces itself. Run the vhs recipe in a repo whose poster.png comes
# from the Playwright scene and the poster is deleted and never put back --
# green exit code, a clip on disk, a file gone (THE-282, found on a demo whose
# two README stills lived here).
#
# So: remember what was in there, and on the way out put back anything the run
# did not rebuild, then fail saying which. Restoring rather than only reporting
# is the point. A documented command must not leave the tree missing a
# committed file, and that has to hold on the failure paths too -- a recipe
# that dies halfway is exactly when the directory is empty -- which is why this
# is an EXIT trap and not a check written after the recording.
SNAPSHOT=""
LOST=""
restore_unrebuilt() {
  local status=$?
  local rel
  [ -n "$SNAPSHOT" ] || return "$status"
  while IFS= read -r rel; do
    if [ -z "$rel" ] || [ -e "$OUT_DIR/$rel" ]; then continue; fi
    mkdir -p "$(dirname "$OUT_DIR/$rel")"
    cp -a "$SNAPSHOT/$rel" "$OUT_DIR/$rel"
    LOST="$LOST  $rel
"
  done <<EOF
$(cd "$SNAPSHOT" && find . -type f | sed 's|^\./||' | sort)
EOF
  rm -rf "$SNAPSHOT"
  SNAPSHOT=""
  if [ -z "$LOST" ]; then return "$status"; fi
  echo "record.sh: this run did not rebuild what was already in ${OUT_DIR#"$REPO_ROOT"/}:" >&2
  printf '%s' "$LOST" >&2
  cat >&2 <<'WHY'
They have been put back, so the tree is not missing them -- but they are now
older than the clip beside them, and that is a lie waiting to ship. A file kept
in this directory has to be produced by the recording, because the recording
wipes the directory first. Either make this run produce it, or keep it
somewhere record.sh does not delete. If you are recording a second recipe here,
give it its own directory with DEMO_OUT_DIR rather than letting it compete for
this one.
WHY
  if [ "$status" -eq 0 ]; then status=1; fi
  exit "$status"
}
trap restore_unrebuilt EXIT

say "recording with $RECIPE"
if [ -d "$OUT_DIR" ]; then
  SNAPSHOT="$(mktemp -d)"
  cp -a "$OUT_DIR/." "$SNAPSHOT/"
fi
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
recipe_record "$OUT_DIR"

CLIP="$RECIPE_CLIP"
if [ -z "$CLIP" ]; then
  CLIP="$(find "$OUT_DIR" -maxdepth 1 -type f \( -name '*.gif' -o -name '*.mp4' \) | sort | head -1)"
fi
if [ -z "$CLIP" ] || [ ! -s "$CLIP" ]; then
  echo "record.sh: the $RECIPE recipe produced no clip" >&2
  exit 1
fi

if command -v ffprobe >/dev/null 2>&1; then
  DURATION="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$CLIP" 2>/dev/null || echo "")"
else
  DURATION=""
fi

for file in "$OUT_DIR"/*; do
  [ -f "$file" ] || continue
  say "wrote ${file#"$REPO_ROOT"/} ($(du -h "$file" | cut -f1))"
done

if [ -n "$DURATION" ] && [ "${DURATION%.*}" -gt "$MAX_SECONDS" ]; then
  echo "record.sh: clip is ${DURATION%.*}s, over the ${MAX_SECONDS}s budget" >&2
  exit 1
fi
say "clip is ${DURATION%.*}s, inside the ${MAX_SECONDS}s budget"
